services:
 redis:
   image: redis:6.2
   container_name: recruiter-dev-redis
   ports:
     - "6379:6379"
   volumes:
     - redis_data:/data
 selenium:
   image: selenium/standalone-chrome:latest
   container_name: recruiter-dev-selenium
   ports:
     - "14440:4444"
   environment:
     - SE_NODE_ENABLE_MANAGED_DOWNLOADS=true
     - SE_OPTS=--enable-managed-downloads true
     - SE_LOG_LEVEL=INFO
   #      - SE_BROWSER_ARGS_INCOGNITO=--incognitos
   restart: always
   shm_size: 4gb

 backend:
   build:
     context: ./backend
   container_name: recruiter-dev-backend
   command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 7013
   ports:
     - "18000:7013"
   volumes:
     - ./backend:/backend
   depends_on:
     - selenium
     - redis
   environment:
     - REDIS_HOST=${REDIS_HOST:-redis}
     - REDIS_PORT=${REDIS_PORT:-6379}
     - REMOTE_DRIVER_URL=${REMOTE_DRIVER_URL:-http://selenium:4444/wd/hub}
   healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7013/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

 tests:
   build:
     context: ./backend
   container_name: recruiter-dev-tests
   command: >
     sh -c "
       cd /backend &&
       poetry run pytest -v --maxfail=1 --disable-warnings --tb=short
     "
   volumes:
     - ./backend:/backend
   depends_on:
    backend:
      condition: service_healthy
    selenium:
      condition: service_started
    redis:
      condition: service_started
   environment:
     - REDIS_HOST=${REDIS_HOST:-redis}
     - REDIS_PORT=${REDIS_PORT:-6379}
     - REMOTE_DRIVER_URL=${REMOTE_DRIVER_URL:-http://selenium:4444/wd/hub}
     - PYTEST_ADDOPTS="-v"
     - PYTHONPATH=/backend

 n8n:
   image: n8nio/n8n
   container_name: recruiter-dev-n8n
   ports:
     - "5678:5678"
   environment:
     - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
     - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
     - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
     - N8N_HOST=${N8N_HOST:-localhost}
     - N8N_PORT=${N8N_PORT:-5678}
     - REDIS_HOST=${REDIS_HOST:-redis}
     - REDIS_PORT=${REDIS_PORT:-6379}
     - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE:-false}
     - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED:-true}
   volumes:
     - ./workflows:/workflows
     - n8n_data:/home/node/.n8n
   depends_on:
     - backend
   entrypoint: >
      sh -c "
        n8n import:workflow --input /workflows/n8n_workflow.json &&
        n8n import:credentials --input /workflows/n8n_credentials.json &&
        n8n update:workflow --id VV8VW3wNzoXBoF1L --active=true &&
        n8n update:workflow --id Y0kyqHk3gar46LaE --active=true &&
        n8n start
      "

 frontend:
   build:
     context: ./frontend
   container_name: recruiter-dev-frontend
   ports:
     - "3000:80"
  #  volumes:
  #    - ./frontend:/frontend
  #  environment:
  #    - VITE_REACT_N8N_URL=${VITE_REACT_N8N_URL}
   depends_on:
     - n8n

volumes:
 redis_data:
 n8n_data:
